# Define base image
FROM continuumio/miniconda3
 
# Set working directory for the project
WORKDIR /Users/renee/Documents/WIS_Spr22/SM_Rot/Syclop-MINE
 
 
# Create Conda environment from the YAML file
COPY environment.yml .
RUN conda env create -f environment.yml
 
# Override default shell and use bash
SHELL ["conda", "run", "-n", "drift3nv.8", "/bin/bash", "-c"]
 
# Activate Conda environment and check if it is working properly
RUN echo "Making sure pytorch is installed correctly..."
RUN python -c "import torch"
 
# Python program to run in the container
COPY . .
ENTRYPOINT ["conda", "run", "--no-capture-output","-n", "env", "python", "DriftMINERun.py"]
